### ISSUE TITLE
Data distribution

### ISSUE THREAD

**Issue by MatisseBE** [OpenRailwayMap/OpenRailwayMap-api#3]
This isn't really about the API, but it fits better here than the "normal" repo.

Could the API provide easy access to the rail data itself? (Oh that sounds stupid, that's what an API is supposed to do)

Here is my use:

I'd like to make some simple drawings using My Maps on Google maps. But there seems no simple way to get just the rail data (into KML or any other format).

Ideally, you could download certain attributes (lines, stations) in multiple formats (geojson/kml/etc..) or download only between x and y coordinates. 

(Any other ideas are also welcome!)

**Comment by Nakaner** [comment]
OpenRailwayMap uses OSM data, you can get that data for free in various formats (raw OSM data, filtered and reorganised GIS formats) from various sources. See https://github.com/OpenRailwayMap/OpenRailwayMap/issues/624#issuecomment-398412706 for details.

I do not want to offer the data via the API as well because it will increase the work load of the administrator to deal with abuse of the API while a bulk download exists (this is already the case for Overpass API).

There are plans for a vector data download feature. They are tracked at https://github.com/OpenRailwayMap/OpenRailwayMap/issues/860 because it is out of scope of the API.
